# Generated by Django 5.1.1 on 2024-09-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payments_link_payments_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_amount',
            field=models.PositiveIntegerField(help_text='Сумма оплаты в рублях', verbose_name='Сумма оплаты'),
        ),
    ]
