# Generated by Django 5.1.1 on 2024-09-08 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название курса', max_length=255, verbose_name='Название курса')),
                ('description', models.TextField(help_text='Введите описание курса', verbose_name='Описание курса')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='photo/course/', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название урока', max_length=255, verbose_name='Название урока')),
                ('description', models.TextField(help_text='Введите описание урока', verbose_name='Описание урока')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='photo/lesson/', verbose_name='картинка')),
                ('video_link', models.CharField(blank=True, help_text='Введите ссылку на видео', max_length=255, null=True, verbose_name='Ссылка на видео')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='materials.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
            },
        ),
    ]
