# Generated by Django 5.1.1 on 2024-09-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.CharField(default=1, help_text='Введите имя владельца курса', max_length=255, verbose_name='Владелец'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='owner',
            field=models.CharField(default=1, help_text='Введите имя владельца урока', max_length=255, verbose_name='Владелец'),
            preserve_default=False,
        ),
    ]
