# Generated by Django 5.1.1 on 2024-09-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Введите описание курса', null=True, verbose_name='Описание курса'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, help_text='Введите описание урока', null=True, verbose_name='Описание урока'),
        ),
    ]
